import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Navbar from "@/components/navbar";
import { webBlocksDataset } from "@/constants/data";
import { Toaster } from "sonner";

const manrope = Manrope({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Pup App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased`}>
        <StoreProvider>
          <Navbar navigation={webBlocksDataset.navigationData} />
          <main className="">
            {children}
            <Toaster />
          </main>
        </StoreProvider>
      </body>
    </html>
  );
}
